version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8000"
    depends_on:
      - user-service
      - post-service

  user-service:
    build: ./user-service
    expose:
      - "8000"

  post-service:
    build: ./post-service
    expose:
      - "8000"
